### ISSUE TITLE
比命令行效果略差一点点

### ISSUE THREAD

**Issue by sunzongzheng** [GangZhuo/kcptun-gui-windows#10]
实测命令行执行
client -r sever:port -l :localport -key key -fast3
看Youtube 1080P流畅，用gui会卡。
命令行峰值可以到1.5M/s，gui只能到1.3M/s

**Comment by GangZhuo** [comment]
关闭流量统计。

Suen <notifications@github.com>于2017年2月2日周四 下午3:18写道：
