### ISSUE TITLE
启动后托盘图标为黑色，必须手动启动kcptun

### ISSUE THREAD

**Issue by tx9191** [GangZhuo/kcptun-gui-windows#11]
切换服务器时托盘图标也会变黑，须要通过托盘图标右键菜单手动启动kcptun。
图标意外变黑时log里提示：

> System.NullReferenceException: 未将对象引用设置到对象的实例。
>    在 kcptun_gui.Controller.MainController.Reload()
> 

这是这几天才出现的，之前并未出现这种状况，不知道是不是.net framework的问题，系统为64位Windows10

**Comment by GangZhuo** [comment]
不能重现.

**Comment by V-E-O** [comment]
Utils.GetTempPath(TrafficStatistics.TRAFFIC_STATISTICS_FILE)的内容可能为null
反序列化后导致this._trafficStatistics = TrafficStatistics.Load(); == null
所以void MainController.Reload()
this.traffic = this._trafficStatistics.GetTrafficLog(currentServer);会抛异常, 提个PR试试

**Comment by xcl010** [comment]
我也有同样的问题，启动日志
[2017-03-01 11:50:43] os suspend
[2017-03-01 12:24:29] os wake up
[2017-03-01 12:24:34] System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 kcptun_gui.Controller.MainController.Reload()

每次开机启动都不自动运行服务，得手动启动kcptun

**Comment by GangZhuo** [comment]
试试 https://ci.appveyor.com/project/GangZhuo/kcptun-gui-windows/branch/master 中基于最新代码自动编译的版本。 @V-E-O 修好了这个问题。
