### ISSUE TITLE
期望完善一下功能

### ISSUE THREAD

**Issue by ghost** [GangZhuo/kcptun-gui-windows#4]
1.实现双击托盘图标启用或禁用KCPTun的功能。
2.加大“客户端参数”的显示区，让参数信息能一次性显示完全，可以考虑减小服务列表区。
3.去除参数设置区上方的三个功能按钮，没有什么实用价值。如果是因为是控件自带，可否考虑用其它控件（如文本）加以覆盖。
![qq 20160910005253](https://cloud.githubusercontent.com/assets/13914490/18395981/cf2f6ad0-76f3-11e6-809e-702db3f1ac17.jpg)

另外个人小要求，能否提供指定配置文件功能，即可否另命名配置文件，也可实现原KCPTun配置文件通用。其实可以在原KCPTun配置文件json中加键值对就行，不用改原json格式，新加对像。

**Comment by GangZhuo** [comment]
感谢你的建议。
- 双击托盘图标后启用和禁用功能看起来有点不合理，而且右击后选择启用或禁用也不会多花多少时间。我修改为双击后弹出配置窗口。
- 如果参数显示不全的话，可以拖动窗口边框来改变窗口的大小。
- 既然窗口大小可以改变，那么三个功能按钮放和不放也没有多少区别，但是切换到按字母排序后，对于不熟悉的人可以快速按照字符顺序来找到选项。
- 既然通过 GUI 来管理客户端了，那么应该不必要和原本的配置兼容了。现有的方式，更容易管理多服务器。我增加了一个导出服务器配置到文件的功能，见 https://ci.appveyor.com/project/GangZhuo/kcptun-gui-windows/branch/master/job/1m3i83ti3cecl00h/artifacts 。
