### ISSUE TITLE
请教一下流量统计的实现

### ISSUE THREAD

**Issue by ragnaroks** [GangZhuo/kcptun-gui-windows#8]
你好,我是KcptunGUI的开坑人,以前写了kcptungui的半成品,后来看到你的更易用,同时家里出了事情,导致停止更新了(后来项目被别人fork去并且加入了我没来得及实现的服务器端模式).

现在闲下来了,正在重写KcptunGUI,这期间遇到一个问题,就是如何统计到流量,
据我所知,kcptun-gui-windows不但可以统计到kcptun的流量,并且可以统计到实际传输流量.

我经过尝试,发现除非使用winpcap或类似的第三方库才能统计到,所以想请教一下kcptun-gui-windows的实现方法,如果愿意的话,烦请告知.(还没看源码,当前还在着手UI布局)

**Comment by ragnaroks** [comment]
刚才看了一下代码,发现是转发到kcptun-gui-windows来处理了,我之前也设想这样处理,但是这样获得的应该只有从被代理的应用程序到kcptun-gui-Windows这段的流量,也就是"实际流量",kcptun的流量是怎么获得的?

**Comment by GangZhuo** [comment]
在 kcptun 的两端都加了转发。即浏览器流量进入 tcp 转发器，然后进入 kcptun, 然后再次进入 UDP
转发器，最后进入远端服务器。这样可在两个转发器中统计实际流量和 kcptun 流量

Ragnaroks <notifications@github.com>于2017年1月2日周一 下午9:42写道：

**Comment by ragnaroks** [comment]
昨天晚上了解到新版本kcptun已经可以输出snmplog了,或许可以基于日志来统计kcptun的流量.
感谢你的协助.
